const express = require("express");
const router = express.Router();
const CartController = require("../controllers/cartController");
router.get("/get/:customerId", CartController.getAllByCustomerId);
router.post("/add/:customerId", CartController.addToCart);
router.delete("/update", CartController.removeFromCart);
router.put("/update", CartController.updateCartItem);
router.delete("/update", CartController.removeFromCart);
router.delete("/clear", CartController.clearCart);
module.exports = router;
